### ISSUE TITLE
Error in module.json - value should be array not string...

### ISSUE THREAD

**Issue by WildBillLives** [kandashi/Dynamic-Effects-SRD#1]
Using Foundry v0.66 - D&D5E v0.96 : The r module can be installed, but it does not show up in the listing of my D&D 5E game to be activated as a module  due to an issue with the 'module.json' file.

"From _KaKaRoTo_ (Forge admin):     "systems": "dnd5e", 
Looks like the module.json is invalid, it should be an array, not a string"  (_KaKaRoTo_ tested out as well with the same result)

**Comment by Jonwh25** [comment]
request to change module.json to use this instead:

"systems": ["dnd5e"],

**Comment by kandashi** [comment]
Sorted, thanks for the catch
