### ISSUE TITLE
Unarmored Defense (Monk) DAE SRD 0.2.0 

### ISSUE THREAD

**Issue by beck99an** [kandashi/Dynamic-Effects-SRD#10]
Effect Value is "10 + @abilities.wis.mod @abilities.dex.mod", missing a + between the two ability mods. Thanks!

**Comment by kandashi** [comment]
Ahhh, one I missed in the mad dash to fix everything this morning, thanks for the heads up

**Comment by kandashi** [comment]
Fixed in new update
