### ISSUE TITLE
Rage advantage on strength saves/checks

### ISSUE THREAD

**Issue by Merudo** [kandashi/Dynamic-Effects-SRD#101]
Barbarian rage currently only gives a +2 to melee damage, however the damage should instead depend on level.
```
Level 1-8: +2 damage
Level 9-15: +3 damage
Level 16-20: +4 damage
```
Also, currently Rage doesn't give advantage to strength saving throws and ability checks, which it could do using midi-qol flags
```
flags.midi-qol.advantage.ability.check.str
flags.midi-qol.advantage.ability.save.str
```

**Comment by kandashi** [comment]
I wont be automating the levelup damage, that is for the player/DM to adjust (similar to the core effect), however the advantage on saves/checks I can add in

**Comment by Merudo** [comment]
> I wont be automating the levelup damage, that is for the player/DM to adjust (similar to the core effect)

Why not change the flat +2 to the actual correct calculation:

`(@classes.barbarian.levels < 16 ? ceil(@classes.barbarian.levels/8)+1 : 4)`

**Comment by kandashi** [comment]
Because this fails at the moment due to changes in the string parsing

**Comment by Merudo** [comment]
> Because this fails at the moment due to changes in the string parsing

It works fine in 0.7.10. Is this issue new to 0.8.x?

**Comment by kandashi** [comment]
Yes, at least I believe so. I will check again

**Comment by kandashi** [comment]
This does seem to work. Will go out in the 0.8.6 release
