### ISSUE TITLE
AC Auto Calculation for Heavy Armor

### ISSUE THREAD

**Issue by jadrian2006** [kandashi/Dynamic-Effects-SRD#102]
Dex modifier for heavy armor not properly calculated.

In the case of 8 dex (-1 modifier) under normal light/medium armor the -1 applies to your AC
When you are wearing heavy armor, this does not apply. 

A character with str 8, -1 dex wearing full plate should have 18 ac, DAE calculates it as 17.

**Comment by kandashi** [comment]
You want DAE not DAE SRD
