### ISSUE TITLE
Confusion spell

### ISSUE THREAD

**Issue by siliconsaint** [kandashi/Dynamic-Effects-SRD#103]
Foundry 0.8.6, with latest module updates.

Confusion spell is throwing errors each round.  Here's the console output along with chat output.

<img width="615" alt="Screen Shot 2021-06-13 at 2 44 16 PM" src="https://user-images.githubusercontent.com/56798973/121818619-4f9ee800-cc56-11eb-9d4b-9e6254ca2bc9.png">
<img width="237" alt="Screen Shot 2021-06-13 at 2 45 24 PM" src="https://user-images.githubusercontent.com/56798973/121818624-54fc3280-cc56-11eb-845a-b43474f4d9d8.png">

Also, the comments in the ItemMacro seem to indicate something should be passed? But the config isn't passing any arguments.  Not sure if that is a problem.

<img width="722" alt="Screen Shot 2021-06-13 at 2 45 58 PM" src="https://user-images.githubusercontent.com/56798973/121818638-6d6c4d00-cc56-11eb-912d-293172b8eb4e.png">

**Comment by kandashi** [comment]
Still not updated to 0.8.6 ;)

**Comment by siliconsaint** [comment]
👍 Thought I saw it updated in the last few days, sorry!

**Comment by kandashi** [comment]
The macro in my macros repo is updated, just not the srd
