### ISSUE TITLE
Feature/Question - Remove reference to the furnace module

### ISSUE THREAD

**Issue by p4535992** [kandashi/Dynamic-Effects-SRD#105]
The module [Furnace](https://github.com/League-of-Foundry-Developers/fvtt-module-furnace) is been deprecated for FoundryVTT 0.8.6 , its successor for the advanced macro mechanism is [Advanced Macros](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros).

Any reference to the Furnace module should be removed, in favor of the new one?

**Comment by kandashi** [comment]
Hum, i thought I had, it appears that chagne didnt make it through. will fix

**Comment by p4535992** [comment]
Nono excuse me I expressed myself very badly, I meant only the reference on the readme.md in the code i dont' see (at least for me) any reference to the furnace!

**Comment by kandashi** [comment]
Yeah, that's what I understood. It should be gone now
