### ISSUE TITLE
spiritual weapon appears broken

### ISSUE THREAD

**Issue by SR5060** [kandashi/Dynamic-Effects-SRD#107]
the spiritual weapon spell does not appear to do anything when run (v8.6). DAE and item macro settings were reviewed and don't appear to be missing anything

**Comment by thatlonelybugbear** [comment]
Can you import and try this one?
[fvtt-Item-spiritual-weapon.zip](https://github.com/kandashi/Dynamic-Effects-SRD/files/6687923/fvtt-Item-spiritual-weapon.zip)

**Comment by SR5060** [comment]
actually this may be an issue caused by item macro module. It looks like the hook is not triggering for any macros

**Comment by SR5060** [comment]
ok got item macro working but now I'm getting an error thrown with the spell (the imported one). Looks like it's not retrieving the tokenID. didn't modify any of the attributes of the spell (self cast, DAE settings are set standardly)

![image](https://user-images.githubusercontent.com/85184490/122825879-23174b80-d2a8-11eb-983f-4b2d704f7144.png)

**Comment by kandashi** [comment]
Yeah, this is a DAE bug im aware of. Im going to be waiting to see if Tim fixes it on his end before updating anything else

**Comment by SR5060** [comment]
Ok yea that makes sense, I was testing some other items that were working last week and they are throwing errors too, so probably best if he's able to fix it.
