### ISSUE TITLE
DAE spells reconfigured

### ISSUE THREAD

**Issue by thatlonelybugbear** [kandashi/Dynamic-Effects-SRD#108]
Please find attached some spells that now work with Foundry 0.8.7, DnD5e-1.3.5, DAE 0.8.19 and Midi-QOL 0.8.19

Flame Blade, Spiritual Weapon, Moonblade, Magic Weapon
[DAE spells.zip](https://github.com/kandashi/Dynamic-Effects-SRD/files/6687959/DAE.spells.zip)

**Comment by kandashi** [comment]
closed due to upstream DAE fix
