### ISSUE TITLE
Rage damage string not working

### ISSUE THREAD

**Issue by Shyvor** [kandashi/Dynamic-Effects-SRD#110]
The rage damage calculation string doesn't seem to work on my end, which was added based on issue #101 Attack rolls won't work due to it when rage is active.

See attached screenshot for error.

Versions: 5e: 1.3.6 
Foundry: 0.8.8 
DAE SRD: 5.0.01
DAE: 0.8.30

On the right DAE SRD's Rage.
On the left: Post import / character add rage
On the bottom: Error of the roll
![afbeelding](https://user-images.githubusercontent.com/705408/126036053-1e812fb6-adbc-49d8-a8df-cac6224ba471.png)

The error itself: 
![afbeelding](https://user-images.githubusercontent.com/705408/126036000-538e4caf-d9fc-4cc1-8cf0-7d3c517da5b2.png)

**Comment by Shyvor** [comment]
Please ignore, for some reason my install had betterrolls AND midi installed while i don't recall installing better rolls myself.
Solved by disabling better rolls

**Comment by Shyvor** [comment]
tested again with Betterrolls disabled: 
![afbeelding](https://user-images.githubusercontent.com/705408/126036245-fb902e8a-a7df-4b8f-9b59-052ec23c7387.png)

**Comment by supernun** [comment]
It looks like it might be because ternary operators are no longer supported for rolls:
https://gitlab.com/foundrynet/foundryvtt/-/issues/4973

**Comment by supernun** [comment]
It should probably be changed to 
```javascript
(floor(abs((@classes.barbarian.levels-2)/7))+2)
```

**Comment by supernun** [comment]
Also:
```javascript
flags.midi-qol.fail.ability.save.str
```

should be 
```javascript
flags.midi-qol.advantage.ability.save.str
```

and
```javascript
flags.midi-qol.fail.ability.check.str
```
should be 

```javascript
flags.midi-qol.advantage.ability.check.str
```

**Comment by Shyvor** [comment]
tested the above mentioned fix and it solved the error
