### ISSUE TITLE
 Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by un-boxing-man** [kandashi/Dynamic-Effects-SRD#115]
chrome is saying "
Manifest file is missing or unreadable
Could not load manifest."

**Comment by un-boxing-man** [comment]
![image](https://user-images.githubusercontent.com/54999078/138019854-de7e152f-f7f5-41f6-b041-d5ed344cb2f0.png)

**Comment by kandashi** [comment]
I doupt this is an issue with the module as there are 9k valid downloads
