### ISSUE TITLE
Sneak Attack not working properly

### ISSUE THREAD

**Issue by ravingdragoon** [kandashi/Dynamic-Effects-SRD#116]
It seems that Sneak Attack is not functioning when the rogue attacks with advantage and there are no allies within 5 feet of the target. Is this intentional and/or not implementable?

![image](https://user-images.githubusercontent.com/72875320/140770693-7c346dc7-bbba-4fbd-9726-e6b7e244f750.png)

**Comment by kandashi** [comment]
This is not covered by the DAE SRD sneak attack, you'll want the Midi Sample Items one
