### ISSUE TITLE
Mage Armour active effect

### ISSUE THREAD

**Issue by M0nk3yy** [kandashi/Dynamic-Effects-SRD#117]
The Midi SRD entry is using _data.attributes.ac.base OVERRIDE 13_. This doesn't seem to do anything when the character's armour calculation mode is set to "Equipped Armour" - which for most characters would be the primary default.

I suggest instead using _data.attributes.ac.calc OVERRIDE mage_ which will alter the in-use calculation to be the preset Mage Armour calculation.

![image](https://user-images.githubusercontent.com/66137312/142599841-f8748104-8f7a-4360-b7c1-994a6f0d3b15.png)

**Comment by kandashi** [comment]
wrong github im afraid ;)

(ill sort in the midi srd)
