### ISSUE TITLE
Needs updated for V9

### ISSUE THREAD

**Issue by MSanteler** [kandashi/Dynamic-Effects-SRD#118]
:D

**Comment by markmillerlv** [comment]
Is there any progress being made on this?

**Comment by kandashi** [comment]
marked as compatible

**Comment by MSanteler** [comment]
Is it actually compatible though?

**Comment by kandashi** [comment]
Oh no, I've just changed the comparability for fun /s

There shouldn't be any reason it shouldn't work.

**Comment by markmillerlv** [comment]
Thanks so much.

**Comment by MSanteler** [comment]
That makes sense since I only opened this issue for fun - and not because things weren’t working for after the upgrade /s

**Comment by MSanteler** [comment]
Though I cannot find any examples now so I will defer to your expertise. Thank you for the module
