### ISSUE TITLE
Heroes' Feast Spell

### ISSUE THREAD

**Issue by Bryn1701** [kandashi/Dynamic-Effects-SRD#18]
When you try to use the Heroes' Feast spell, the macro element kicks up an error(I had all the players targeted for the feast). Here is the console error in question. The rest of the DAE works fine. 

https://gyazo.com/2e90ec1d93506d579cf850bb814a6098

Thanks.

**Comment by kandashi** [comment]
I cant seem to replicate this on my end, just checking that you have Furnace with advanced macros enabled. If so, could you PM me a list of your modules on Discord?
