### ISSUE TITLE
Simple Typo "Criitical"

### ISSUE THREAD

**Issue by DM-Shenanigans** [kandashi/Dynamic-Effects-SRD#26]
The Attribute Key Drop-down includes "Flags Melee Criitical Dice". It should read "Flags Melee Critical Dice".

![Criitical](https://user-images.githubusercontent.com/73723196/100032976-0cf6ea80-2dae-11eb-89d0-9ef68d077ae0.png)

**Comment by kandashi** [comment]
This is an issue with DAE directly not the SRD pack, you can log an issue here: https://gitlab.com/tposney/dae
