### ISSUE TITLE
Cloak of Protection

### ISSUE THREAD

**Issue by Fenaldar** [kandashi/Dynamic-Effects-SRD#27]
If I equip the Cloak of Protection and unequip it several times, it gives everytime +1, so I have +1 +1 +1 +1 +1 +1 at the end.

at the Cloak remove the ""
{"key":"data.bonuses.abilities.save","value":"+1","mode":0,"priority":20}

{"key":"data.bonuses.abilities.save","value":1,"mode":0,"priority":20}

**Comment by kandashi** [comment]
This sounds like a module incompatability. With DAE 0.2.24 and DAE SRD 3.0.3 I cannot replicate this behavoiur (and there is no "" in the SRD Item
![image](https://user-images.githubusercontent.com/1347785/100435514-f0043500-3095-11eb-847e-b6cf06e81d3b.png)
