### ISSUE TITLE
Rage is applied to selected token, but should only be applied to self

### ISSUE THREAD

**Issue by hhu94** [kandashi/Dynamic-Effects-SRD#29]
I fixed it by adding choosing the Action Type Utility in the Feature Attack section. Left is the default, right is the fixed version.
![image](https://user-images.githubusercontent.com/7145349/100551585-88d1b680-3236-11eb-8307-7931848a8b86.png)

**Comment by kandashi** [comment]
This appears to be DAE functionality, not the item configuration. I can replicate even with the Utility action type selected
