### ISSUE TITLE
Monk feature "Unarmored Movement" not present

### ISSUE THREAD

**Issue by phildias** [kandashi/Dynamic-Effects-SRD#31]
The monk's "Unarmored Movement" feature (Pages 26 and 27 of the SRD 5.1: https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf) is not listed. 
The feature adds a few feet to the character's walking movement. This should be added as a passive effect.

Thanks for the awesome work, btw!!!!

**Comment by jegasus** [comment]
I just figured out how to get this formula to work!!!!
You can use the following:
`max(10+(ceil(((@classes.monk.levels)-5)/4))*5,10)`
This will set the appropriate increases to the monk's walking speed based on the actor's monk level.
