### ISSUE TITLE
Aid Spell issue

### ISSUE THREAD

**Issue by Brimcon** [kandashi/Dynamic-Effects-SRD#32]
Aid spell sets HP only to Caster's modified Max HP, both at the start of the cast and when the spell fades using abouttime, time's up, and Calendar to force the 8 hours to pass.

**Comment by kandashi** [comment]
Can you give more steps to replicate this, as I cannot

**Comment by Brimcon** [comment]
Have a character with 9 Max hit points cast Aid on characters with 10 or more base HP. It helps to have something like Combat Numbers to display changes in HP.

Aid spell sets the targets HP to 14.

8 Hours later, their Max HP returns to normal, but now targets have 9 HP.
![image](https://user-images.githubusercontent.com/7198283/103141705-fb567a80-46ac-11eb-9907-443ad7a990d6.png)

**Comment by kandashi** [comment]
Ahh yes, i see what you mean now

**Comment by kandashi** [comment]
fixed in 4.0.31 release
