### ISSUE TITLE
[Bug] Effects of Cloak of Protection won't turn on/off when equipped/unequipped

### ISSUE THREAD

**Issue by jegasus** [kandashi/Dynamic-Effects-SRD#37]
My character is attuned to the Cloak of Protection from the DAE-SRD, but its effect does not turn on/off when the item is actually equipped/unequipped.
When I manually turn the effect on (in the actor's Effects tab), the effect actually does turn on and the actor's AC really does increase. But if I unequip the Cloak and equip it again, the effect just never turns on.

I'm not sure if this is an issue with the original DAE package or the specific implementation of the Cloak of Protection here, so I opened up an issue in both places. Here is a link to the issue on the DAE gitlab page: https://gitlab.com/tposney/dae/-/issues/86

**Comment by kandashi** [comment]
I cant replicate this bug. Can you send the actor and item json over

**Comment by jegasus** [comment]
Here is a character equipped with the cloak and where the bug is happening: https://www.dropbox.com/s/5vmhyzn62wnnbxy/fvtt-Actor-Test_character.json?dl=0

Thanks for looking into this!!!

**Comment by kandashi** [comment]
It looks like this is an old version of the Cloak of Protection, the new version has "attunement required" instead of  "attunement not required", I would check your foundry, dnd5e, DAE and DAE SRD versions are up to date and try with a new item from the compendium pack

**Comment by kandashi** [comment]
The same actor with a new version item works fine in my tests

**Comment by jegasus** [comment]
Yep, you're right - it was something related to some old version. I just updated everything on my side and it worked. Sorry for wasting your time with this! And thanks again for looking into it =]

**Comment by kandashi** [comment]
No problem
