### ISSUE TITLE
Darkvision macro recalls wrong flag.

### ISSUE THREAD

**Issue by spirritus** [kandashi/Dynamic-Effects-SRD#44]
When the macro activates it correctly changes the vision of the token.
However deactivation does not change the token vision back to the original value.
I assume this happens because the initial state is stored in the token:
`target.setFlag('world', 'darkvisionSpell', dimVision);`
However the recalled states queries the actor:
`let sight = target.actor.getFlag('world', 'darkvisionSpell');`

I assume the state should always be stored and recalled form the actor.

**Comment by spirritus** [comment]
Also, the initial query of dim sight was undefined. This macro here should adress all issues:

```
//DAE Macro Execute, Effect Value = "Macro Name" @target
let target = canvas.tokens.get(args[1]);
let dimVision = target.data.dimSight;
console.log(target);
if (args[0] === "on") {
    target.actor.setFlag('world', 'darkvisionSpell', dimVision);
    target.update({"dimSight" : 60 });
    ChatMessage.create({content: `${target.name}'s vision has been improved`});
}
if(args[0] === "off") {
    let sight = target.actor.getFlag('world', 'darkvisionSpell');
    target.update({"dimSight" : sight });
    target.actor.unsetFlag('world', 'darkvisionSpell');
    ChatMessage.create({content: `${target.name}'s vision has been returned`});
}
```

**Comment by kandashi** [comment]
Ah shoot, I locally fixed this, but apparently didnt push the new version
