### ISSUE TITLE
Suggestion: add a suffix to item's name indicating that they are automated

### ISSUE THREAD

**Issue by Fraxinus1753** [kandashi/Dynamic-Effects-SRD#63]
I think it would be helpful if automated spells, items and feats in the DAE SRD compendiums had something in their name indicating that they are automated (for instance a D or A in parenthesis at the end or something like that). That way, it is possible to easily know when to expect an automated behavior or not, or which of our actors' owned items are automated and which ones are not and should be replaced by the DAE SRD version. 

However I suppose this would require you to go over every item one by one, and maybe I'm the only one who would find that useful, so I'd totally undestand if this wasn't considered.

Cheers and thanks for the great module!

**Comment by kandashi** [comment]
Im afraid this isnt possible for another reason too. Many mass replace functions look at names when replacing data, this wouldnt be possible with this addition. Everything in the DAE SRD is automated to some extent (auto update on equip, attune, attack etc)
