### ISSUE TITLE
Slippers of Spider Climbing

### ISSUE THREAD

**Issue by aestrada4355** [kandashi/Dynamic-Effects-SRD#65]
Hello, not really a bug, but an inquiry, trying to understand DAE and the SRD for my own items.

The Slippers presently ADD movement.climb = to movement.walk, but I wonder if the effect would not be better suited with UPGRADE rather than ADD.

If the PC already has Climb speed of, lets say 10, they will get a total of 40 with the slippers, if they have a Walk speed of 30, but should only get Climb speed UP to their walk speed. Unless I misread the description of the slippers.

**Comment by kandashi** [comment]
oh yes that is correct. I will adjust and it'll go in the next release
