### ISSUE TITLE
Unable to activate Dynamic Active Effects SRD - cannot activate dependency DAE

### ISSUE THREAD

**Issue by davco9200** [kandashi/Dynamic-Effects-SRD#79]
Hi! I am eager to try out Dynamic effects, but running into an installation issue.

Steps to reproduce:

1. Go to Foundry/ Install New Module
2. Search for "Dynamic Active Effects"
3. Install "Dynamic Active Effects SRD" - System asks to install "Dynamic Active Effects" - accept
4. Launch Gameworld
5. Manage Modules
6. Activate Dynamic Active Effects SRD; save.
7. Foundry asks: This module has 1 dependency... would you like to enable?" - Click yes
8. Click Save Module settings; get error "You have enabled the module Dynamic Active Effects SRD, but it's dependencies are not enabled!" but there's no other options. 
I made a quick screen recording of the last few steps. https://www.dropbox.com/s/1z7l7qy43rem0cv/Dynamic%20Active%20Effects%20error.mov?dl=0
Any suggestions?
Colin

**Comment by kandashi** [comment]
Update your dnd5e version as DAE is only avaliable for the latest version
