### ISSUE TITLE
Cannot add effect to spell

### ISSUE THREAD

**Issue by phil-the-dev** [kandashi/Dynamic-Effects-SRD#80]
New to foundry and I'm trying to apply an effect to a spell and I keep getting this error `Cannot read property 'effects' of null`. I've attached a screenshot with hopefully any relevant info on the spell in question. It was an DDB imported spell. All modules/systems are updated.

![DAE issue](https://user-images.githubusercontent.com/1228950/110651355-5dd9f580-8189-11eb-8070-88854b22ed8a.png)

**Comment by kandashi** [comment]
This is not a support channel for module questions. I'll direct you to the foundry discord, specifically the #module-discussion channel https://discord.gg/foundryvtt
