### ISSUE TITLE
Bless upcast support (3 targets)

### ISSUE THREAD

**Issue by gatesvp** [kandashi/Dynamic-Effects-SRD#86]
### Problem description

Bless can target "up to 3 creatures" when cast at 1st level. However, it also says:

> When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.

But when I target 4 creatures and attempt to cast Bless, I get the following message.

> You must target at most 3 token(s) before rolling the attack

### Expected behaviour

When casting Bless with more than 3 targets, the spell should proceed as normal with two exceptions:

 - The spell slots drop-down should only include slot of the appropriate level.
 - If there are not such slots the available, the caster should be informed and the casting dialog should not appear

**Comment by kandashi** [comment]
That is not a thing from this module, you'll want https://gitlab.com/tposney/midi-qol
