### ISSUE TITLE
Misty Step Temporary Effect

### ISSUE THREAD

**Issue by john3300** [kandashi/Dynamic-Effects-SRD#93]
The Misty Step spell currently has a temporary effect, duration 1 turn, that doesn't seem to do anything.  Based on the official wording of the spell in DDB I don't see any kind of status effect that it applies.  So I don't think this temporary effect should be on the spell at all.  Am I missing something?

**Comment by kandashi** [comment]
This is how the macro is triggered

**Comment by john3300** [comment]
OK, I do see the `macro.itemMacro` in the effects now.  Please excuse my ignorance here but what macro is this executing?

**Comment by SR5060** [comment]
I believe misty step might have broken with v8.6, though I hadn't used it prior to upgrading

**Comment by kandashi** [comment]
> I believe misty step might have broken with v8.6, though I hadn't used it prior to upgrading

No macro in the DAE SRD will work in  0.8.6, that's why the compatability is 0.7.9

**Comment by john3300** [comment]
I'm still on 0.7 so that's not a problem for me.  But where do I find the macro this is supposed to be executing?

**Comment by kandashi** [comment]
@john3300 it's embedded in the item using item macro

**Comment by john3300** [comment]
Is there a way for me to see the code of this embedded macro?

**Comment by kandashi** [comment]
If you install the Item Macro module you can yes

**Comment by john3300** [comment]
According to the Item Macro [module listing page](https://foundryvtt.com/packages/itemacro) v1.3.2 is the last one to be compatible with the 0.7.x branch.  But all the Manifest URL links on that page all point to the same URL for the v1.5.2 release.  Can I still get the older version somehow?

**Comment by kandashi** [comment]
Best head to the discord page for that help. Im going to close this ticket now
