### ISSUE TITLE
Heroes' Feast

### ISSUE THREAD

**Issue by siliconsaint** [kandashi/Dynamic-Effects-SRD#94]
This is the message I'm seeing for any targeted by Heroes' Feast.

<img width="229" alt="Screen Shot 2021-06-02 at 3 59 10 PM" src="https://user-images.githubusercontent.com/56798973/120544890-f0bab280-c3bb-11eb-8d5c-ee3e4ff9257b.png">

**Comment by kandashi** [comment]
0.8.6 ?

**Comment by siliconsaint** [comment]
Sorry, 7.10.

**Comment by kandashi** [comment]
This is due to clicking `apply active effects` and not `damage` as far as i can tell

**Comment by siliconsaint** [comment]
I target myself and cast the spell. Midi is fast forwarding everything so I do not interact with the card.
Is that the question?

![Screen Shot 2021-06-11 at 2 44 32 PM](https://user-images.githubusercontent.com/56798973/121735095-a627ed00-cac3-11eb-9d81-1c4e499740be.png)

**Comment by kandashi** [comment]
I can't test in 0.7.10, but it will be working in 0.8.6

**Comment by siliconsaint** [comment]
NP, thanks Kandashi!  As soon as my GM updates to 8.6 I will too ;)
